-- liquibase formatted sql

-- changeset weilai:comfy-tables
-- comment ComfyUI 业务表（7 张）：实例/工作流/计划/批次/任务/尝试/输出

CREATE TABLE IF NOT EXISTS `comfy_instance` (
    `id`                  bigint        NOT NULL AUTO_INCREMENT          COMMENT 'ID',
    `user_id`             bigint        NOT NULL                         COMMENT '用户ID',
    `name`                varchar(100)  NOT NULL                         COMMENT '实例名称',
    `endpoint_url`        varchar(512)  NOT NULL                         COMMENT 'ComfyUI 地址（HTTP/HTTPS）',
    `endpoint_hash`       char(64)      NOT NULL                         COMMENT '地址哈希（SHA-256 十六进制文本）',
    `device_uuid`         varchar(64)   NOT NULL                         COMMENT '设备UUID（站点存储随机标识，非硬件身份）',
    `config_revision`     bigint        NOT NULL DEFAULT 0              COMMENT '地址或设备变化时的配置版本（递增）',
    `page_uuid`           varchar(64)   DEFAULT NULL                    COMMENT '当前执行页UUID（启用本页执行后写入）',
    `login_token_digest`  binary(32)     DEFAULT NULL                    COMMENT '登录令牌摘要（SHA-256 原始字节）',
    `lease_epoch`         bigint        NOT NULL DEFAULT 0              COMMENT '执行租约递增 epoch',
    `lease_status`        tinyint       UNSIGNED NOT NULL DEFAULT 2     COMMENT '执行租约状态（1：在线/ACTIVE；2：离线/OFFLINE）',
    `lease_expires_at`    datetime(3)   DEFAULT NULL                    COMMENT '租约到期时间（UTC）',
    `last_heartbeat_at`   datetime(3)   DEFAULT NULL                    COMMENT '最后心跳时间（UTC）',
    `status`              tinyint       UNSIGNED NOT NULL DEFAULT 1     COMMENT '实例状态（1：启用；2：禁用）',
    `create_user`         bigint        DEFAULT NULL                    COMMENT '创建人',
    `create_time`         datetime      NOT NULL                        COMMENT '创建时间',
    `update_user`         bigint        DEFAULT NULL                    COMMENT '修改人',
    `update_time`         datetime      DEFAULT NULL                    COMMENT '修改时间',
    `deleted`             bigint        NOT NULL DEFAULT 0              COMMENT '是否已删除（0：否；id：是）',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_comfy_instance_user_endpoint`(`user_id`, `endpoint_hash`),
    INDEX `idx_comfy_instance_user_lease`(`user_id`, `lease_status`),
    INDEX `idx_comfy_instance_device`(`device_uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ComfyUI 实例表';

CREATE TABLE IF NOT EXISTS `comfy_workflow` (
    `id`                  bigint        NOT NULL AUTO_INCREMENT          COMMENT 'ID',
    `user_id`             bigint        NOT NULL                         COMMENT '用户ID',
    `name`                varchar(100)  NOT NULL                         COMMENT '工作流名称',
    `description`         varchar(255)  DEFAULT NULL                     COMMENT '描述',
    `raw_workflow_json`   longtext       DEFAULT NULL                    COMMENT '普通 UI workflow JSON',
    `api_prompt_json`     longtext       NOT NULL                        COMMENT 'API prompt JSON（执行格式）',
    `node_bindings_json`  longtext       DEFAULT NULL                    COMMENT '参数绑定（nodeId/classType/inputName/类型）',
    `config_revision`     bigint        NOT NULL DEFAULT 0              COMMENT '工作流配置版本（递增）',
    `status`              tinyint       UNSIGNED NOT NULL DEFAULT 1     COMMENT '状态（1：草稿；2：就绪）',
    `create_user`         bigint        DEFAULT NULL                    COMMENT '创建人',
    `create_time`         datetime      NOT NULL                        COMMENT '创建时间',
    `update_user`         bigint        DEFAULT NULL                    COMMENT '修改人',
    `update_time`         datetime      DEFAULT NULL                    COMMENT '修改时间',
    `deleted`             bigint        NOT NULL DEFAULT 0              COMMENT '是否已删除（0：否；id：是）',
    PRIMARY KEY (`id`),
    INDEX `idx_comfy_workflow_user`(`user_id`),
    INDEX `idx_comfy_workflow_status`(`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ComfyUI 工作流表';

CREATE TABLE IF NOT EXISTS `comfy_schedule` (
    `id`                    bigint        NOT NULL AUTO_INCREMENT          COMMENT 'ID',
    `user_id`               bigint        NOT NULL                         COMMENT '用户ID',
    `name`                  varchar(100)  NOT NULL                         COMMENT '计划名称',
    `instance_id`           bigint        NOT NULL                         COMMENT '固定目标实例ID',
    `workflow_id`           bigint        NOT NULL                         COMMENT '来源工作流ID',
    `run_mode`              varchar(20)   NOT NULL                         COMMENT '运行方式（ONCE/DAILY/WEEKLY/INTERVAL，后端白名单语义）',
    `timezone`              varchar(64)   NOT NULL                         COMMENT 'IANA 时区',
    `rule_json`             longtext       DEFAULT NULL                    COMMENT '结构化运行规则',
    `fixed_target_json`     longtext       DEFAULT NULL                    COMMENT '固定目标快照（原地址及设备）',
    `execution_snapshot_json` longtext     NOT NULL                        COMMENT '完整执行快照（API prompt+节点绑定+参数）',
    `params_json`           longtext       DEFAULT NULL                    COMMENT '公共参数与逐项覆盖',
    `material_refs_json`    longtext       DEFAULT NULL                    COMMENT '素材引用',
    `task_count_per_run`    int           NOT NULL DEFAULT 1              COMMENT '每次任务数量',
    `backlog_limit`         int           NOT NULL DEFAULT 1000           COMMENT '积压上限',
    `next_run_at_utc`       datetime(3)   DEFAULT NULL                     COMMENT '下一次计划触发时间（UTC）',
    `scan_cursor_utc`       datetime(3)   DEFAULT NULL                     COMMENT '补执行游标（UTC）',
    `has_unmaterialized`    bit(1)        DEFAULT b'0'                      COMMENT '是否存在未物化到期区间（存在时拒绝编辑/暂停/归档）',
    `status`                tinyint       UNSIGNED NOT NULL DEFAULT 4     COMMENT '状态（1：ACTIVE；2：BLOCKED；3：PAUSED；4：DRAFT；5：ARCHIVED）',
    `config_revision`       bigint        NOT NULL DEFAULT 0              COMMENT '计划配置版本（递增）',
    `create_user`           bigint        DEFAULT NULL                    COMMENT '创建人',
    `create_time`           datetime      NOT NULL                        COMMENT '创建时间',
    `update_user`           bigint        DEFAULT NULL                    COMMENT '修改人',
    `update_time`           datetime      DEFAULT NULL                    COMMENT '修改时间',
    `deleted`               bigint        NOT NULL DEFAULT 0              COMMENT '是否已删除（0：否；id：是）',
    PRIMARY KEY (`id`),
    INDEX `idx_comfy_schedule_user_status`(`user_id`, `status`),
    INDEX `idx_comfy_schedule_next_run`(`status`, `next_run_at_utc`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ComfyUI 用户计划表';

CREATE TABLE IF NOT EXISTS `comfy_task_batch` (
    `id`                       bigint        NOT NULL AUTO_INCREMENT          COMMENT 'ID',
    `user_id`                  bigint        NOT NULL                         COMMENT '用户ID',
    `schedule_id`              bigint        DEFAULT NULL                     COMMENT '来源计划ID（手动批次为 NULL）',
    `instance_id`              bigint        NOT NULL                         COMMENT '目标实例ID',
    `workflow_id`              bigint        NOT NULL                         COMMENT '来源工作流ID',
    `scheduled_at_utc`         datetime(3)   NOT NULL                         COMMENT '触发时刻（UTC）',
    `rule_json`                longtext       DEFAULT NULL                    COMMENT '复制的运行规则',
    `execution_snapshot_json`  longtext       NOT NULL                         COMMENT '复制的完整执行快照',
    `task_count`               int           NOT NULL DEFAULT 0              COMMENT '任务项数量',
    `request_key`              varchar(64)   DEFAULT NULL                     COMMENT '请求键（user_id+request_key 防重复创建）',
    `status`                   tinyint       UNSIGNED NOT NULL DEFAULT 1     COMMENT '状态（1：等待；2：部分；3：完成；4：失败）',
    `create_user`              bigint        DEFAULT NULL                    COMMENT '创建人',
    `create_time`              datetime      NOT NULL                        COMMENT '创建时间',
    `update_user`              bigint        DEFAULT NULL                    COMMENT '修改人',
    `update_time`              datetime      DEFAULT NULL                    COMMENT '修改时间',
    `deleted`                  bigint        NOT NULL DEFAULT 0              COMMENT '是否已删除（0：否；id：是）',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_comfy_batch_schedule_scheduled`(`schedule_id`, `scheduled_at_utc`),
    UNIQUE INDEX `uk_comfy_batch_user_request`(`user_id`, `request_key`),
    INDEX `idx_comfy_batch_user_scheduled`(`user_id`, `scheduled_at_utc`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ComfyUI 任务批次表';

CREATE TABLE IF NOT EXISTS `comfy_task` (
    `id`                  bigint        NOT NULL AUTO_INCREMENT          COMMENT 'ID',
    `user_id`             bigint        NOT NULL                         COMMENT '用户ID',
    `schedule_id`         bigint        DEFAULT NULL                     COMMENT '来源计划ID',
    `task_batch_id`       bigint        NOT NULL                         COMMENT '所属批次ID',
    `instance_id`         bigint        NOT NULL                         COMMENT '目标实例ID',
    `workflow_id`         bigint        NOT NULL                         COMMENT '来源工作流ID',
    `item_index`          int           NOT NULL DEFAULT 1              COMMENT '任务项序号（从1开始）',
    `scheduled_at_utc`    datetime(3)   DEFAULT NULL                     COMMENT '计划触发时间（UTC）',
    `actual_params_json`  longtext       DEFAULT NULL                    COMMENT '展开的实际参数、种子及素材引用',
    `final_prompt_json`   longtext       DEFAULT NULL                    COMMENT '冻结的最终 prompt',
    `endpoint_url`        varchar(512)  DEFAULT NULL                     COMMENT '原目标地址（从快照，不随实例变更改变）',
    `target_device_uuid`  varchar(64)   DEFAULT NULL                     COMMENT '原目标设备UUID',
    `status`              tinyint       UNSIGNED NOT NULL DEFAULT 1     COMMENT '任务状态',
    `version_no`          bigint        NOT NULL DEFAULT 0              COMMENT '乐观锁版本号',
    `current_attempt_no`  int           NOT NULL DEFAULT 0              COMMENT '当前尝试号（未执行为0）',
    `claim_token`         varchar(64)   DEFAULT NULL                     COMMENT '领取令牌',
    `claim_page_uuid`     varchar(64)   DEFAULT NULL                     COMMENT '领取页UUID',
    `claim_device_uuid`   varchar(64)   DEFAULT NULL                     COMMENT '领取设备UUID',
    `claim_epoch`         bigint        DEFAULT NULL                     COMMENT '领取时租约epoch',
    `claimed_at`          datetime(3)   DEFAULT NULL                     COMMENT '领取时间（UTC）',
    `submitted_at`        datetime(3)   DEFAULT NULL                     COMMENT '提交时间（UTC）',
    `prompt_id`           varchar(64)   DEFAULT NULL                     COMMENT 'ComfyUI promptId',
    `finished_at`         datetime(3)   DEFAULT NULL                     COMMENT '完成时间（UTC）',
    `create_user`         bigint        DEFAULT NULL                    COMMENT '创建人',
    `create_time`         datetime      NOT NULL                        COMMENT '创建时间',
    `update_user`         bigint        DEFAULT NULL                    COMMENT '修改人',
    `update_time`         datetime      DEFAULT NULL                    COMMENT '修改时间',
    `deleted`             bigint        NOT NULL DEFAULT 0              COMMENT '是否已删除（0：否；id：是）',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_comfy_task_batch_item`(`task_batch_id`, `item_index`),
    INDEX `idx_comfy_task_user_status`(`user_id`, `status`),
    INDEX `idx_comfy_task_batch_status`(`task_batch_id`, `status`),
    INDEX `idx_comfy_task_status_scheduled`(`status`, `scheduled_at_utc`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ComfyUI 任务表';

CREATE TABLE IF NOT EXISTS `comfy_task_attempt` (
    `id`                  bigint        NOT NULL AUTO_INCREMENT          COMMENT 'ID',
    `user_id`             bigint        NOT NULL                         COMMENT '用户ID',
    `task_id`             bigint        NOT NULL                         COMMENT '所属任务ID',
    `task_batch_id`       bigint        NOT NULL                         COMMENT '所属批次ID',
    `attempt_no`          int           NOT NULL DEFAULT 1              COMMENT '尝试号（从1开始）',
    `request_uuid`        binary(16)    DEFAULT NULL                     COMMENT '请求UUID（原始字节）',
    `request_key`         varchar(64)   DEFAULT NULL                     COMMENT '请求键（防重复/乱序回报）',
    `actual_prompt_json`  longtext       DEFAULT NULL                    COMMENT '实际提交的 prompt',
    `send_intent`         tinyint       UNSIGNED NOT NULL DEFAULT 1     COMMENT '发送意图（1：提交；2：重试；3：对账；4：取消）',
    `request_meta_json`   longtext       DEFAULT NULL                    COMMENT '请求元数据',
    `response_json`       longtext       DEFAULT NULL                    COMMENT '响应内容',
    `error_msg`           varchar(512)  DEFAULT NULL                     COMMENT '错误信息',
    `status`              tinyint       UNSIGNED NOT NULL DEFAULT 1     COMMENT '尝试状态（1：发送中；2：成功；3：失败；4：未知）',
    `version_no`          bigint        NOT NULL DEFAULT 0              COMMENT '乐观锁版本号',
    `create_user`         bigint        DEFAULT NULL                    COMMENT '创建人',
    `create_time`         datetime      NOT NULL                        COMMENT '创建时间',
    `update_user`         bigint        DEFAULT NULL                    COMMENT '修改人',
    `update_time`         datetime      DEFAULT NULL                    COMMENT '修改时间',
    `deleted`             bigint        NOT NULL DEFAULT 0              COMMENT '是否已删除（0：否；id：是）',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_comfy_attempt_task_no`(`task_id`, `attempt_no`),
    UNIQUE INDEX `uk_comfy_attempt_request_key`(`request_key`),
    INDEX `idx_comfy_attempt_task`(`task_id`, `attempt_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ComfyUI 任务提交尝试表';

CREATE TABLE IF NOT EXISTS `comfy_task_output` (
    `id`                 bigint        NOT NULL AUTO_INCREMENT          COMMENT 'ID',
    `user_id`            bigint        NOT NULL                         COMMENT '用户ID',
    `task_id`            bigint        NOT NULL                         COMMENT '所属任务ID',
    `task_batch_id`      bigint        NOT NULL                         COMMENT '所属批次ID',
    `attempt_id`         bigint        DEFAULT NULL                     COMMENT '来源尝试ID',
    `filename`           varchar(512)  DEFAULT NULL                     COMMENT '输出文件名',
    `subfolder`          varchar(512)  DEFAULT NULL                     COMMENT '输出子目录',
    `type`               varchar(64)   DEFAULT NULL                     COMMENT '输出类型（ComfyUI type）',
    `node_id`            varchar(64)   DEFAULT NULL                     COMMENT '产出节点ID',
    `endpoint_url`       varchar(512)  DEFAULT NULL                     COMMENT '原目标地址（从任务快照，不随实例变更改变）',
    `media_info_json`    longtext       DEFAULT NULL                    COMMENT '媒体信息',
    `collect_status`     tinyint       UNSIGNED NOT NULL DEFAULT 1     COMMENT '收集状态（1：PENDING；2：COMPLETE；3：ERROR）',
    `availability`       tinyint       UNSIGNED NOT NULL DEFAULT 1     COMMENT '可用性（1：可用；2：不可用；3：已删除）',
    `version_no`         bigint        NOT NULL DEFAULT 0              COMMENT '乐观锁版本号',
    `create_user`        bigint        DEFAULT NULL                    COMMENT '创建人',
    `create_time`        datetime      NOT NULL                        COMMENT '创建时间',
    `update_user`         bigint        DEFAULT NULL                    COMMENT '修改人',
    `update_time`         datetime      DEFAULT NULL                    COMMENT '修改时间',
    `deleted`            bigint        NOT NULL DEFAULT 0              COMMENT '是否已删除（0：否；id：是）',
    PRIMARY KEY (`id`),
    INDEX `idx_comfy_output_task`(`task_id`),
    INDEX `idx_comfy_output_user_task`(`user_id`, `task_id`),
    INDEX `idx_comfy_output_attempt`(`attempt_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ComfyUI 任务输出表';
